{% set name = "modAL" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b520ff8c214a99a35c015220d585df49010214a657d376ba680f6cd69a8341f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.13
    - python
    - scikit-learn >=0.18
    - scipy >=0.18

test:
  imports:
    - modAL
    - modAL.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/modAL/
  summary: A modular active learning framework for Python3
  license: MIT
  # License requested to be included as part of package
  # https://github.com/modAL-python/modAL/issues/87
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
