{% set name = "modAL" %}
{% set version = "0.4.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/modAL-python/modAL-python-{{ version }}.tar.gz
  sha256: b184dad157bbc58f92e688835a4885fd48413312661c1a24b9575bcfee9d9ad1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.13
    - python >={{ python_min }}
    - scikit-learn >=0.18
    - scipy >=0.18
    - pandas

test:
  imports:
    - modAL
    - modAL.models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/modAL/
  summary: A modular active learning framework for Python3
  license: MIT
  # License requested to be included as part of package
  # https://github.com/modAL-python/modAL/issues/87
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
